export const MOVE_DISTANCE = 20;
export const JUMP_DISTANCE = 300;

export const ACTION_DISTANCE = 197;
export const ACTION_DISTANCE_SQUARED = ACTION_DISTANCE * ACTION_DISTANCE;
export const ORIGINAL_ACTION_DISTANCE_SQUARED = 200 * 200;
export const SIGHT_DISTANCE = 397;
export const SIGHT_DISTANCE_SQUARED = SIGHT_DISTANCE * SIGHT_DISTANCE;
export const ORIGINAL_SIGHT_DISTANCE_SQUARED = 400 * 400;

export const MERGE_DISTANCE_SQUARED = 20 * 20;

export const MAX_MERGE_COUNT = 100;

export const OUTPOST_USAGE = 1;
export const OUTPOST_RANGE = 400;
export const OUTPOST_ADDITIONAL_THRESHOLD = 500;
export const OUTPOST_ADDITIONAL_USAGE = 2;
export const OUTPOST_ADDITIONAL_RANGE = 600;

export const BASE_STAR_INIT_ENERGY = 100;
export const STAR_CONSTANT_REGEN = 3;
export const STAR_PERCENT_REGEN = 0.01;
export const STAR_MAX_ENERGY = 1000;
export const MIDDLE_STAR_START_TICK = 100;

export const MAX_X = 4400;
export const MAX_Y = 2700;
