export const MOVE_DISTANCE = 20;
export const JUMP_DISTANCE = 300;

export const ACTION_DISTANCE = 197;
export const ACTION_DISTANCE_SQUARED = ACTION_DISTANCE * ACTION_DISTANCE;
export const ORIGINAL_ACTION_DISTANCE_SQUARED = 200 * 200;
export const SIGHT_DISTANCE = 397;
export const SIGHT_DISTANCE_SQUARED = SIGHT_DISTANCE * SIGHT_DISTANCE;
export const ORIGINAL_SIGHT_DISTANCE_SQUARED = 400 * 400;

export const MAX_X = 4400;
export const MAX_Y = 2700;
